remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list (if)
title: [Hi! I am Jawad]
description:
  [
    This website is about my professional journey ,
    and any key insights I want to share with the world
  ]
